### ISSUE TITLE
Undefined index: SCRIPT_URI

### ISSUE THREAD

**Issue by BassemN** [there4/php-analytics-event#1]
Hello,

I'm getting the below error. Please advise

`Notice: Undefined index: SCRIPT_URI in vendor/there4/php-analytics-event/src/There4/Analytics/AnalyticsEvent.php on line 97`

Thanks,

**Comment by craig-davis** [comment]
You've found some vintage code! Are you running this from a command line script? That would cause that `SCRIPT_URI` to be unset. We probably need to a little update to the script to account for that.

**Comment by BassemN** [comment]
I run this from browser under this url `http://localhost/test/` Kindly check my `$_SERVER` dump below.
I think  we can use `REQUEST_URI` instead

```
Array
(
    [HTTP_HOST] => localhost
    [HTTP_CONNECTION] => keep-alive
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch
    [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.8
    [HTTP_COOKIE] => __atuvc=5%7C31; SESS777106e187863585130e0b679eb662b0=7oRwJFd3JpDrBm2OgBlYnx37gAN8EdRhmHeY1y9ote0
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SERVER_SIGNATURE] => 
Apache/2.4.17 (Ubuntu) Server at localhost Port 80


    [SERVER_SOFTWARE] => Apache/2.4.17 (Ubuntu)
    [SERVER_NAME] => localhost
    [SERVER_ADDR] => 127.0.0.1
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => 127.0.0.1
    [DOCUMENT_ROOT] => /var/www/html
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => /var/www/html
    [SERVER_ADMIN] => webmaster@localhost
    [SCRIPT_FILENAME] => /var/www/html/test/index.php
    [REMOTE_PORT] => 36280
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [REQUEST_URI] => /test/
    [SCRIPT_NAME] => /test/index.php
    [PHP_SELF] => /test/index.php
    [REQUEST_TIME_FLOAT] => 1449587655.681
    [REQUEST_TIME] => 1449587655
)
```

**Comment by craig-davis** [comment]
That's interesting. I think that you'll actually have to build the full uri. I /think/ that `SCRIPT_URI` is the full url, in your case it should be `http://localhost/test/`. Might have to do a little string building to get that in this case. 

If you send a PR, I'd love to have it!

**Comment by BassemN** [comment]
Kindly check this PR https://github.com/there4/php-analytics-event/pull/2

**Comment by craig-davis** [comment]
I've accepted the pull request and made you a maintainer. If you've got more changes to make, make another PR and leave a comment and then feel free to merge and make a release. 

Thanks!
