### ISSUE TITLE
rand() parameters too large (float) warning

### ISSUE THREAD

**Issue by mxdpeep** [there4/php-analytics-event#6]
this fix is not giving a warning:

        $var_utmn    = rand(10000000, 99999999); //random request number
        $var_cookie  = rand(10000000, 99999999); //random cookie number

**Comment by craig-davis** [comment]
Hi @mxdpeep - Do you think that the library needs to be fixed? Is it giving you a warning?

**Comment by mxdpeep** [comment]
Yeap, just make the rand() parameters as integers, I am running in Strict
Mode, so Warnings are not acceptable. But it works as a charm then :D

Thank you!



s pozdravem,

*Filip Oščádal*

**Comment by mxdpeep** [comment]
![image](https://user-images.githubusercontent.com/75358/45878217-92327f00-bda0-11e8-9458-0d80d4e0ea6f.png)
